on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - name: Create a .NET Core class library project
        run: dotnet new classlib

      - name: Build package
        run: dotnet pack

      - name: Publish package
        run: dotnet nuget push bin/Debug/*.nupkg
